# Generated by Django 2.2.3 on 2019-07-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
