# Generated by Django 2.2.3 on 2019-07-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('UI Design', 'UI')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
