# Generated by Django 2.2.3 on 2019-07-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tools',
            field=models.CharField(choices=[('Adobe Illustrator', 'Adobe Illustrator'), ('Django', 'Django'), ('React JS', 'React JS')], default='', max_length=300),
            preserve_default=False,
        ),
    ]
