# Generated by Django 2.2.3 on 2019-07-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20190711_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(default='', upload_to='post_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='', upload_to='post_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(default='', upload_to='post_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(default='', upload_to='post_images'),
            preserve_default=False,
        ),
    ]
