# Generated by Django 2.2.3 on 2019-07-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20190711_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image5',
            field=models.ImageField(default='', upload_to='post_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image6',
            field=models.ImageField(default='', upload_to='post_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default='', upload_to='post_images'),
            preserve_default=False,
        ),
    ]
