# Generated by Django 2.2.3 on 2019-07-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20190711_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank='True', upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank='True', upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank='True', upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank='True', upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image5',
            field=models.ImageField(blank='True', upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image6',
            field=models.ImageField(blank='True', upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank='True', upload_to='post_images'),
        ),
    ]
