# Generated by Django 2.2.3 on 2019-07-30 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='phone',
        ),
    ]
